export const lessons = [
  {
    id: '1',
    title: 'Strong Passwords',
    description: 'Learn how to create and manage strong passwords to protect your accounts.',
    content: 'A strong password is at least 12 characters long and includes a mix of letters, numbers, and symbols.',
    example: 'Example of a strong password: P@ssw0rd123!',
    interactiveCheck: 'Rate the strength of your current password.',
  },
  {
    id: '2',
    title: 'Password Managers',
    description: 'Discover the benefits of using password managers to store and generate passwords securely.',
    content: 'Password managers can help you create unique passwords for every account and store them securely.',
    example: 'Popular password managers include LastPass, 1Password, and Bitwarden.',
    interactiveCheck: 'Have you used a password manager before?',
  },
  {
    id: '3',
    title: 'Two-Factor Authentication (2FA)',
    description: 'Understand the importance of enabling 2FA for an extra layer of security.',
    content: '2FA requires not only a password but also a second factor, such as a text message or authentication app.',
    example: 'Enabling 2FA on your accounts can significantly reduce the risk of unauthorized access.',
    interactiveCheck: 'Have you enabled 2FA on your accounts?',
  },
  {
    id: '4',
    title: 'Phishing',
    description: 'Learn how to recognize and avoid phishing attempts.',
    content: 'Phishing is a method used by attackers to trick you into providing personal information.',
    example: 'Be cautious of emails that ask for sensitive information or contain suspicious links.',
    interactiveCheck: 'Can you identify a phishing email?',
  },
  {
    id: '5',
    title: 'Social Engineering',
    description: 'Understand how social engineering tactics can compromise your security.',
    content: 'Social engineering involves manipulating individuals into divulging confidential information.',
    example: 'Never share personal information over the phone unless you are sure of the caller’s identity.',
    interactiveCheck: 'Have you ever encountered a social engineering attempt?',
  },
  {
    id: '6',
    title: 'Malware',
    description: 'Learn about different types of malware and how to protect your devices.',
    content: 'Malware can include viruses, worms, and ransomware that can harm your devices and data.',
    example: 'Always keep your software updated to protect against malware threats.',
    interactiveCheck: 'Do you have antivirus software installed on your devices?',
  },
  {
    id: '7',
    title: 'Ransomware',
    description: 'Understand what ransomware is and how to prevent it.',
    content: 'Ransomware encrypts your files and demands payment for their release.',
    example: 'Regularly back up your data to avoid losing it to ransomware attacks.',
    interactiveCheck: 'Have you backed up your important files recently?',
  },
  {
    id: '8',
    title: 'Safe Browsing',
    description: 'Learn how to browse the internet safely and securely.',
    content: 'Use secure websites (https://) and avoid clicking on unknown links.',
    example: 'Check for the padlock icon in the address bar before entering sensitive information.',
    interactiveCheck: 'Do you know how to identify secure websites?',
  },
  {
    id: '9',
    title: 'Wi-Fi Security',
    description: 'Understand the risks of using public Wi-Fi and how to secure your connection.',
    content: 'Avoid accessing sensitive information over public Wi-Fi networks without a VPN.',
    example: 'Using a VPN can help protect your data when using public Wi-Fi.',
    interactiveCheck: 'Do you use a VPN when connecting to public Wi-Fi?',
  },
  {
    id: '10',
    title: 'Mobile Security',
    description: 'Learn how to secure your mobile devices against threats.',
    content: 'Keep your mobile operating system and apps updated, and use security features like biometric locks.',
    example: 'Enable remote wipe features in case your device is lost or stolen.',
    interactiveCheck: 'Have you enabled security features on your mobile device?',
  },
  {
    id: '11',
    title: 'Email Security',
    description: 'Understand how to secure your email accounts and recognize threats.',
    content: 'Use strong passwords and enable 2FA for your email accounts to enhance security.',
    example: 'Be cautious of unsolicited emails asking for personal information.',
    interactiveCheck: 'Do you regularly review your email security settings?',
  },
  {
    id: '12',
    title: 'Data Privacy',
    description: 'Learn how to protect your personal data online.',
    content: 'Be mindful of the information you share on social media and other platforms.',
    example: 'Adjust privacy settings on social media to limit who can see your information.',
    interactiveCheck: 'Have you reviewed your privacy settings on social media recently?',
  },
  {
    id: '13',
    title: 'Safe Online Shopping',
    description: 'Understand how to shop online securely and avoid scams.',
    content: 'Use secure payment methods and shop only on reputable websites.',
    example: 'Look for reviews and ratings before making a purchase online.',
    interactiveCheck: 'Do you check for secure payment options when shopping online?',
  },
  {
    id: '14',
    title: 'Social Media Security',
    description: 'Learn how to secure your social media accounts and recognize threats.',
    content: 'Use strong passwords and be cautious of friend requests from unknown users.',
    example: 'Regularly review your friend list and remove suspicious accounts.',
    interactiveCheck: 'Have you set up alerts for unrecognized logins on your social media accounts?',
  },
  {
    id: '15',
    title: 'Device Updates',
    description: 'Understand the importance of keeping your devices updated.',
    content: 'Regular updates can fix security vulnerabilities and improve performance.',
    example: 'Enable automatic updates on your devices to stay protected.',
    interactiveCheck: 'Do you regularly check for updates on your devices?',
  },
  {
    id: '16',
    title: 'Backups',
    description: 'Learn how to back up your data to prevent loss.',
    content: 'Regular backups can save your data in case of hardware failure or cyber attacks.',
    example: 'Use cloud storage or external drives for backups.',
    interactiveCheck: 'Have you backed up your data in the last month?',
  },
];